In [ ]:
import pandas as pd
df= pd.read_csv("/content/pakwheels_used_car_data_v02.csv")

In [ ]:
df.head()

,addref,city,assembly,body,make,model,year,engine,transmission,fuel,color,registered,mileage,price
0,7943732,Peshawar,NaN,Sedan,Toyota,Corolla,2013.0,1300.0,Manual,Petrol,Silver Metallic,Lahore,145000,2870000.0
1,7730314,Lahore,NaN,Sedan,Honda,City,2000.0,1300.0,Manual,Petrol,Blue,Lahore,230000,995000.0
2,7943737,Lahore,NaN,Sedan,Toyota,Yaris,2021.0,1300.0,Manual,Petrol,Super White,Punjab,60500,3585000.0
3,7943733,Lahore,NaN,Hatchback,Suzuki,Swift,2017.0,1300.0,Manual,Petrol,Grey,Islamabad,87000,2250000.0
4,7923484,Lahore,NaN,Sedan,Honda,Civic,2017.0,1800.0,Automatic,Petrol,Grey,Lahore,86000,4850000.0

In [ ]:
df.describe()

             addref          year        engine         mileage         price
count  7.787800e+04  73099.000000  77875.000000    77878.000000  7.729500e+04
mean   7.809878e+06   2012.812610   1408.072550    91109.192750  3.883232e+06
std    2.599523e+05      7.516685    704.459947    89275.336173  5.759480e+06
min    2.748970e+05   1990.000000      3.000000        1.000000  1.100000e+05
25%    7.805760e+06   2007.000000   1000.000000    34000.000000  1.450000e+06
50%    7.865805e+06   2015.000000   1300.000000    80000.000000  2.700000e+06
75%    7.910334e+06   2019.000000   1600.000000   123456.000000  4.500000e+06
max    7.943741e+06   2022.000000  15000.000000  1000000.000000  5.290000e+08

In [ ]:
df.isnull().sum()

addref              0
city                0
assembly        53689
body             8904
make                0
model               0
year             4779
engine              3
transmission        0
fuel              906
color            1480
registered          0
mileage             0
price             583
dtype: int64

In [ ]:
body_mode= df.body.mode()
body_mode[0]

'Sedan'

In [ ]:
df["body"]= df["body"].fillna(body_mode[0])

In [ ]:
year_mean= df.year.mean()
year_mean

2012.8126102956264

In [ ]:
df["year"]= df["year"].fillna(year_mean)

In [ ]:
engine_mean= df.engine.mean()
engine_mean

1408.0725501123595

In [ ]:
df["engine"]= df["engine"].fillna(engine_mean)

In [ ]:
fuel_mode= df.fuel.mode()
fuel_mode[0]

'Petrol'

In [ ]:
df["fuel"]= df["fuel"].fillna(fuel_mode[0])

In [ ]:
color_mode= df.color.mode()
color_mode[0]

'White'

In [ ]:
df["color"]= df["color"].fillna(color_mode[0])

In [ ]:
price_mean= df.price.mean()
price_mean

3883231.761433469

In [ ]:
df["price"]= df["price"].fillna(price_mean)

In [ ]:
df= df.drop(["assembly","registered"], axis=1)

In [ ]:
df.isnull().sum()

addref          0
city            0
body            0
make            0
model           0
year            0
engine          0
transmission    0
fuel            0
color           0
mileage         0
price           0
dtype: int64

In [ ]:
df.head()

,addref,city,body,make,model,year,engine,transmission,fuel,color,mileage,price
0,7943732,Peshawar,Sedan,Toyota,Corolla,2013.0,1300.0,Manual,Petrol,Silver Metallic,145000,2870000.0
1,7730314,Lahore,Sedan,Honda,City,2000.0,1300.0,Manual,Petrol,Blue,230000,995000.0
2,7943737,Lahore,Sedan,Toyota,Yaris,2021.0,1300.0,Manual,Petrol,Super White,60500,3585000.0
3,7943733,Lahore,Hatchback,Suzuki,Swift,2017.0,1300.0,Manual,Petrol,Grey,87000,2250000.0
4,7923484,Lahore,Sedan,Honda,Civic,2017.0,1800.0,Automatic,Petrol,Grey,86000,4850000.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder= LabelEncoder()

In [ ]:
df["body"]= label_encoder.fit_transform(df["body"])

In [ ]:
df["model"]= label_encoder.fit_transform(df["model"])

In [ ]:
df["transmission"]= label_encoder.fit_transform(df["transmission"])

In [ ]:
df["fuel"]= label_encoder.fit_transform(df["fuel"])

In [ ]:
df["color"]= label_encoder.fit_transform(df["color"])

In [ ]:
df.head()

,addref,city,body,make,model,year,engine,transmission,fuel,color,mileage,price
0,7943732,Peshawar,16,62,121,2013.0,1300.0,1,2,316,145000,2870000.0
1,7730314,Lahore,16,27,109,2000.0,1300.0,1,2,44,230000,995000.0
2,7943737,Lahore,16,62,421,2021.0,1300.0,1,2,345,60500,3585000.0
3,7943733,Lahore,7,60,365,2017.0,1300.0,1,2,167,87000,2250000.0
4,7923484,Lahore,16,27,110,2017.0,1800.0,0,2,167,86000,4850000.0